# Generated by Django 4.0.2 on 2022-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='id_user',
            new_name='user',
        ),
    ]
