# Generated by Django 4.0.2 on 2022-04-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_id_category_categorysubscribers_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='category',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='user',
            new_name='id_user',
        ),
    ]
