# Generated by Django 4.0.2 on 2022-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_ord', '0002_remove_productorder_amount_productorder__amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
    ]
